services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=myBlogDb
      - DB_USER=myBlogUser
      - DB_PASS=rajnish123
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - dev-db-data:/var/lib/postgressql/data
    environment:
      - POSTGRES_DB=myBlogDb
      - POSTGRES_USER=myBlogUser
      - POSTGRES_PASSWORD=rajnish123

volumes:
  dev-db-data:
